### ISSUE TITLE
Addressing the questions/comments in your README

### ISSUE THREAD

**Issue by mandicai** [chbrown/texastribune-salaries#1]
Hello,

Thanks for checking out The Texas Tribune's Government Salaries Explorer. The data you've included in your repository is indeed public information, and is fine to include.

We're in the process of redesigning our salaries explorer — in the future, it will include fewer local governments and school systems. As part of this transition, we're removing some entities from the database.

Also, The Texas Tribune is not a "for-profit entity" — we're a [501(c)3 nonprofit organization](https://www.texastribune.org/about/).

**Comment by chbrown** [comment]
Hi! Thanks for confirming about the license! My bad about the for-profit mischaracterization; I've removed that from the README and otherwise toned down the grumpy commentary in the intro paragraph :/
